[changelog]
body = """
{% for group, commits in commits | group_by(attribute="group") %}\
### {{ group }}
{% for commit in commits %}\
- {{ commit.message | upper_first }}\
{% if commit.breaking %} (**BREAKING**){% endif %} \
([`{{ commit.id | truncate(length=7, end="") }}`](https://github.com/M2Rs-Solutions-LLC/x12-message-exchange-workflow/commit/{{ commit.id }}))
{% endfor %}
{% endfor %}\
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = false
tag_pattern = "v[0-9]*"
sort_commits = "newest"
protect_breaking_commits = true

commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Bug Fixes" },
  { message = "^perf", group = "Performance" },
  { message = "^refactor", group = "Refactoring" },
  { message = "^chore|^ci|^build|^docs|^style|^test", skip = true },
  { message = ".*", group = "Other Changes" },
]